src/xSACdb/urls.py
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views.defaults import page_not_found

admin.autodiscover()

handler400 = 'xsd_frontend.views.handler400'
handler403 = 'xsd_frontend.views.handler403'
handler404 = 'xsd_frontend.views.handler404'
handler500 = 'xsd_frontend.views.handler500'

urlpatterns = [
    url(r'^', include('xsd_frontend.urls', namespace='xsd_frontend')),

    url(r'^members/', include('xsd_members.urls', namespace='xsd_members')),

    url(r'^training/', include('xsd_training.urls', namespace='xsd_training')),

    url(r'^sites/', include('xsd_sites.urls', namespace='xsd_sites')),

    url(r'^trips/', include('xsd_trips.urls', namespace='xsd_trips')),

    url(r'^kit/', include('xsd_kit.urls', namespace='xsd_kit')),

    url(r'^about/', include('xsd_about.urls', namespace='xsd_about')),

    url(r'^help/', include('xsd_help.urls', namespace='xsd_help')),

    # Bodge here as accounts/ URLS need to be avaliable under the xsd_auth
    # namespace along with no namespace for access via external libs #185
    url(r'^accounts/', include('allauth.urls', namespace='xsd_auth')),
    url(r'^accounts/', include('allauth.urls')),

    url(r'^hijack/', include('hijack.urls')),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/rq/', include('django_rq.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^health/', include('health_check.urls')),

    url(r'^404/$', page_not_found),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        # url('^activity/', include('actstream.urls')),
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

src/xsd_frontend/urls.py
from __future__ import unicode_literals

from django.conf.urls import url
from django.contrib.staticfiles.templatetags.staticfiles import static
from django.views.generic import RedirectView, TemplateView

from views import *

favicon_view = RedirectView.as_view(url=static('icons/favicon.ico'), permanent=True)

urlpatterns = [
    url(r'^$', DashboardView.as_view(), name='dashboard'),

    url(r'^accounts/login/$', PreauthLoginView.as_view(), name='login'),
    url(r'^accounts/register/$', PreauthRegisterView.as_view(), name='register'),
    url(r'^accounts/logout/$', logout, name='logout'),

    url(r'^update-request/$', update_request, name='update_request'),

    url(r'^design/$', design, name='design'),

    url(r'^inspect.json$', inspect_api, name='inspect_api'),

    url(r'^favicon\.ico$', favicon_view),
    url(r'manifest\.json$', TemplateView.as_view(
        template_name='browser/manifest.json',
        content_type='application/json'),
        name='app-manifest'
        ),
    url(r'browserconfig\.xml', TemplateView.as_view(
        template_name='browser/browserconfig.xml',
        content_type='application/xml'),
        name='app-browserconfig'
        ),

    url(r'service-worker\.js$', TemplateView.as_view(
        template_name='service-worker.js',
        content_type='text/javascript'),
        name='app-service-worker'),
]

src/xsd_frontend/models.py
from __future__ import unicode_literals

from django.db import models
from django.conf import settings

AREA_CHOICES = (
    ('mem', 'Membership Details and Renewal'),
    ('tra', 'Training Records'),
    ('sit', 'Dive Sites'),
    ('tri', 'Trips'),
)

class UpdateRequest(models.Model):
    area=models.CharField(choices=AREA_CHOICES, max_length=3)
    lesson=models.ForeignKey('xsd_training.Lesson', blank=True, null=True)
    site=models.ForeignKey('xsd_sites.Site', blank=True, null=True)
    request_body=models.TextField()
    response_body=models.TextField(blank=True)
    request_made_by=models.ForeignKey(settings.AUTH_USER_MODEL, related_name='request_made_by', blank=True, null=True)
    response_by=models.ForeignKey(settings.AUTH_USER_MODEL, related_name='response_by', blank=True, null=True)
    completed=models.BooleanField(default=False, verbose_name='Mark this issue as fixed')
    sent=models.DateTimeField(auto_now_add=True)

src/xsd_frontend/forms.py
from __future__ import unicode_literals

from allauth.account.forms import SignupForm
from django import forms

from models import UpdateRequest


class UpdateRequestMake(forms.ModelForm):
    class Meta:
        model = UpdateRequest
        fields = ['area', 'lesson', 'site', 'request_body']


class UpdateRequestReply(forms.ModelForm):
    class Meta:
        model = UpdateRequest
        fields = ['response_body', 'completed']


class ClassicSignupForm(SignupForm):
    first_name = forms.CharField(label='Forename', widget=forms.TextInput(attrs={'placeholder': 'Forename'}))
    last_name = forms.CharField(label='Surname', widget=forms.TextInput(attrs={'placeholder': 'Surname'}))

src/xsd_frontend/templatetags/forms.py
from __future__ import unicode_literals

from django import template

register = template.Library()

@register.filter()
def xsd_field_type(field):
    return field.field.__class__.__name__.lower().replace('field', '')

src/xsd_frontend/views.py
from __future__ import unicode_literals

import hashlib

from allauth.account.views import LoginView, SignupView
from django.conf import settings
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.views.generic import ListView

from forms import UpdateRequestMake, ClassicSignupForm
from xSACdb.build_info import get_time, PRE_FILE, POST_FILE, DEPLOY_FILE
from xSACdb.roles.mixins import RequirePreauth
from xSACdb.version import VERSION
from xsd_frontend.activity import XSDAction


class DashboardView(ListView):
    model = XSDAction
    paginate_by = settings.PAGINATE_BY
    context_object_name = 'feed'

    def get_queryset(self):
        return XSDAction.objects.user(self.request.user)

    def get_template_names(self):
        if self.request.user.profile.verified:
            # Is a verified club member
            return 'frontend/dashboard.html'
        else:
            # Is new
            return 'frontend/unverified_jumbo.html'

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        if self.request.user.profile.verified:
            pass
        return context


class PreauthLoginView(RequirePreauth, LoginView):
    template_name = 'preauth/login.html'


class PreauthRegisterView(RequirePreauth, SignupView):
    template_name = 'preauth/register.html'
    form_class = ClassicSignupForm


from django.contrib.auth import logout as auth_logout


def logout(request):
    # We roll our own logout view as the allauth one needs a POST
    auth_logout(request)
    return redirect('/')


def update_request(request):
    if request.POST:
        form = UpdateRequestMake(request.POST)
        form.data = form.data.copy()
        if form.is_valid():
            ur = form.save()
            ur.request_made_by = request.user
            ur.save()
            return HttpResponse(content="ok")
    response = HttpResponse(content="bad")
    response.status_code = 400
    return response


def design(request):
    return render(request, 'design.html')


def inspect_api(request):
    """API for showing version and build times of instance. Protected with basic key."""
    key = request.GET.get('key', None)
    key_hash = hashlib.sha256('{salt}{key}'.format(salt=settings.INSPECT_API_KEY_SALT, key=key)).hexdigest()

    if key and key_hash == settings.INSPECT_API_KEY_HASH:
        return JsonResponse({
            'version_tag': VERSION['tag'],
            'version_released': VERSION['released'],
            'build_time_pre': get_time(PRE_FILE),
            'build_time_post': get_time(POST_FILE),
            'build_time_deploy': get_time(DEPLOY_FILE),
        })
    else:
        return JsonResponse({
            'error': True,
            'message': 'Missing or invalid key',
        })


def handler400(request):
    return render(request, '500.html', status=400)


def handler403(request):
    return render(request, '403.html', status=403)


def handler404(request):
    return render(request, '404.html', status=404)


def handler500(request):
    return render(request, '500.html', status=500)

src/xsd_training/views/base.py
from __future__ import unicode_literals

from django.core.exceptions import PermissionDenied

from xsd_training.forms import *


class TraineeViewMixin(object):
    def get_trainee(self):
        if 't_pk' in self.kwargs:
            return MemberProfile.objects.get(pk=self.kwargs['t_pk'])
        else:
            return self.request.user.profile

    def is_allowed(self, user):
        return self.get_trainee() == user.profile or is_instructor(user)

    def dispatch(self, request, *args, **kwargs):
        if self.is_allowed(request.user):
            return super(TraineeViewMixin, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied


class TraineeFormMixin(TraineeViewMixin, object):
    def get_context_data(self, **kwargs):
        context = super(TraineeFormMixin, self).get_context_data(**kwargs)
        context['trainee'] = self.get_trainee()
        return context

src/xsd_frontend/templates/preauth/base.html
{% extends 'base_template.html' %}
{% load staticfiles %}

{% block body_class %}xsd-preauth{% endblock %}

{% block content %}
    <div class="xsd-preauth-bg"></div>
    <h1 class="xsd-preauth-logo">
        <a href="{% url 'xsd_frontend:login' %}">
            <img src="{% static 'images/logo.png' %}" alt="{{ l10n_club.name }}" />
        </a>
    </h1>

    <div class="xsd-preauth-login">

        <div class="xsd-preauth-login__social">
            {% include 'preauth/facebook_button.html' %}
        </div>

        <div class="xsd-preauth-login__alternate">
            <div class="xsd-preauth-login__alternate__email">
                <a href="#">Login with Email</a>
            </div>
            <div class="xsd-preauth-login__alternate__register">
                <a href="{% url 'xsd_frontend:register' %}">New member?</a>
            </div>
        </div>

    </div>

{% block preauth_content %}

{% endblock %}
{% endblock %}

src/xsd_frontend/templates/preauth/facebook_button.html
{% load staticfiles %}
{% load socialaccount %}
<a href="{% provider_login_url "facebook" %}" type="button" class="btn btn-primary btn-lg xsd-preauth-facebook">
    <img src="{% static 'images/facebook/FB-f-Logo__white_57.png' %}" />
    Sign in using Facebook
</a>

src/xsd_frontend/templates/preauth/login.html
{% extends 'preauth/base.html' %}
{% load staticfiles %}
{% load socialaccount %}

{% block body_class %}xsd-preauth xsd-preauth--login{% endblock %}

{% block preauth_back %}{% endblock %}

{% block preauth_content %}
    <div class="xsd-preauth-email-login {% if form.errors %}xsd-preauth-email-login--visible{% endif %}">
        <div class="xsd-preauth-email-login__sign-in xsd-preauth-form xsd-preauth-form--login">
            {% include 'preauth/login_form.html' %}
        </div>
    </div>

    <div class="xsd-preauth-content xsd-preauth-content--login">
        <div class="xsd-preauth-content__sign-in xsd-preauth-form xsd-preauth-form--login">
            <h2>Sign in</h2>
            {% include 'preauth/login_form.html' %}
        </div>
        <div class="xsd-preauth-content__onboard">
            <h2>New Here?</h2>
            <p>This is the club database for {{ l10n_club.name }}, to create an account click on the <a href="{% provider_login_url "facebook" %}">Facebook login button</a>, alternatively you can use your <a href="{% url 'xsd_frontend:register' %}">email address</a>.</p>
        </div>
    </div>

    <div class="xsd-preauth-blur {% if form.errors %}xsd-preauth-blur--visible{% endif %}"></div>
{% endblock %}

src/xsd_frontend/templates/preauth/login_form.html
{% load widget_tweaks %}
<form action="." method="POST">
    {% csrf_token %}
    {% if redirect_field_value %}
        <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
    {% endif %}

    {% if form.errors %}
        <p class="xsd-preauth-email-login__errors">Email or password incorrect</p>
    {% endif %}

    <label>
        {% render_field form.login class+="form-control" type="text" placeholder="Email Address" %}
    </label>
    <label>
        {% render_field form.password class+="form-control" %}
    </label>

    <div class="xsd-preauth-form__controls">
        <div>
            <a class="btn btn-secondary-outline"
               href="{% url 'account_reset_password' %}">Forgot password</a>
        </div>
        <div>
            <button class="btn btn-primary" type="submit">Login</button>
        </div>
    </div>

</form>

src/xsd_frontend/templates/preauth/register.html
{% extends 'preauth/base.html' %}

{% block preauth_content %}
    <div class="xsd-preauth-content">

        <p>You can create an account via Facebook or your email address.</p>

        <div class="xsd-preauth-register-facebook">
            {% include 'preauth/facebook_button.html' %}
            <hr/>
        </div>

        <div class="xsd-preauth-form">
            <form action='.' method="POST">
                {% csrf_token %}
                {% if redirect_field_value %}
                    <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
                {% endif %}

                {% with WIDGET_ERROR_CLASS='form-control-danger' WIDGET_REQUIRED_CLASS='my_required' %}
                    {% include 'base/field.html' with field=form.first_name %}
                    {% include 'base/field.html' with field=form.last_name %}
                    {% include 'base/field.html' with field=form.email %}
                    {% include 'base/field.html' with field=form.password1 %}
                {% endwith %}


                <button type="submit"
                        class="btn btn-primary">
                    Create account
                </button>

            </form>
        </div>
    </div>
{% endblock %}