src/xSACdb/urls.py
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views.defaults import page_not_found

admin.autodiscover()

handler400 = 'xsd_frontend.views.handler400'
handler403 = 'xsd_frontend.views.handler403'
handler404 = 'xsd_frontend.views.handler404'
handler500 = 'xsd_frontend.views.handler500'

urlpatterns = [
    url(r'^', include('xsd_frontend.urls', namespace='xsd_frontend')),

    url(r'^members/', include('xsd_members.urls', namespace='xsd_members')),

    url(r'^training/', include('xsd_training.urls', namespace='xsd_training')),

    url(r'^sites/', include('xsd_sites.urls', namespace='xsd_sites')),

    url(r'^trips/', include('xsd_trips.urls', namespace='xsd_trips')),

    url(r'^kit/', include('xsd_kit.urls', namespace='xsd_kit')),

    url(r'^about/', include('xsd_about.urls', namespace='xsd_about')),

    url(r'^help/', include('xsd_help.urls', namespace='xsd_help')),

    # Bodge here as accounts/ URLS need to be avaliable under the xsd_auth
    # namespace along with no namespace for access via external libs #185
    url(r'^accounts/', include('allauth.urls', namespace='xsd_auth')),
    url(r'^accounts/', include('allauth.urls')),

    url(r'^hijack/', include('hijack.urls')),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/rq/', include('django_rq.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^health/', include('health_check.urls')),

    url(r'^404/$', page_not_found),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        # url('^activity/', include('actstream.urls')),
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

src/xsd_frontend/urls.py
from __future__ import unicode_literals

from django.conf.urls import url
from django.contrib.staticfiles.templatetags.staticfiles import static
from django.views.generic import RedirectView, TemplateView

from views import *

favicon_view = RedirectView.as_view(url=static('icons/favicon.ico'), permanent=True)

urlpatterns = [
    url(r'^$', DashboardView.as_view(), name='dashboard'),

    url(r'^accounts/login/$', PreauthLoginView.as_view(), name='login'),
    url(r'^accounts/register/$', PreauthRegisterView.as_view(), name='register'),
    url(r'^accounts/logout/$', logout, name='logout'),

    url(r'^update-request/$', update_request, name='update_request'),

    url(r'^design/$', design, name='design'),

    url(r'^inspect.json$', inspect_api, name='inspect_api'),

    url(r'^favicon\.ico$', favicon_view),
    url(r'manifest\.json$', TemplateView.as_view(
        template_name='browser/manifest.json',
        content_type='application/json'),
        name='app-manifest'
        ),
    url(r'browserconfig\.xml', TemplateView.as_view(
        template_name='browser/browserconfig.xml',
        content_type='application/xml'),
        name='app-browserconfig'
        ),

    url(r'service-worker\.js$', TemplateView.as_view(
        template_name='service-worker.js',
        content_type='text/javascript'),
        name='app-service-worker'),
]

src/xsd_frontend/models.py
from __future__ import unicode_literals

from django.db import models
from django.conf import settings

AREA_CHOICES = (
    ('mem', 'Membership Details and Renewal'),
    ('tra', 'Training Records'),
    ('sit', 'Dive Sites'),
    ('tri', 'Trips'),
)

class UpdateRequest(models.Model):
    area=models.CharField(choices=AREA_CHOICES, max_length=3)
    lesson=models.ForeignKey('xsd_training.Lesson', blank=True, null=True)
    site=models.ForeignKey('xsd_sites.Site', blank=True, null=True)
    request_body=models.TextField()
    response_body=models.TextField(blank=True)
    request_made_by=models.ForeignKey(settings.AUTH_USER_MODEL, related_name='request_made_by', blank=True, null=True)
    response_by=models.ForeignKey(settings.AUTH_USER_MODEL, related_name='response_by', blank=True, null=True)
    completed=models.BooleanField(default=False, verbose_name='Mark this issue as fixed')
    sent=models.DateTimeField(auto_now_add=True)

src/xsd_members/models/fields.py
from django.db import models
from django.forms import forms


class DateOfBirthField(models.DateField):
    def formfield(self, **kwargs):
        defaults = {'form_class': forms.CharField}
        defaults.update(**kwargs)
        return super(DateOfBirthField, self).formfield(**defaults)

src/xsd_frontend/forms.py
from __future__ import unicode_literals

from allauth.account.forms import SignupForm
from django import forms

from models import UpdateRequest


class UpdateRequestMake(forms.ModelForm):
    class Meta:
        model = UpdateRequest
        fields = ['area', 'lesson', 'site', 'request_body']


class UpdateRequestReply(forms.ModelForm):
    class Meta:
        model = UpdateRequest
        fields = ['response_body', 'completed']


class ClassicSignupForm(SignupForm):
    first_name = forms.CharField(label='Forename', widget=forms.TextInput(attrs={'placeholder': 'Forename'}))
    last_name = forms.CharField(label='Surname', widget=forms.TextInput(attrs={'placeholder': 'Surname'}))

src/xsd_frontend/templatetags/forms.py
from __future__ import unicode_literals

from django import template

register = template.Library()

@register.filter()
def xsd_field_type(field):
    return field.field.__class__.__name__.lower().replace('field', '')

src/xsd_frontend/views.py
from __future__ import unicode_literals

import hashlib

from allauth.account.views import LoginView, SignupView
from django.conf import settings
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.views.generic import ListView

from forms import UpdateRequestMake, ClassicSignupForm
from xSACdb.build_info import get_time, PRE_FILE, POST_FILE, DEPLOY_FILE
from xSACdb.roles.mixins import RequirePreauth
from xSACdb.version import VERSION
from xsd_frontend.activity import XSDAction


class DashboardView(ListView):
    model = XSDAction
    paginate_by = settings.PAGINATE_BY
    context_object_name = 'feed'

    def get_queryset(self):
        return XSDAction.objects.user(self.request.user)

    def get_template_names(self):
        if self.request.user.profile.verified:
            # Is a verified club member
            return 'frontend/dashboard.html'
        else:
            # Is new
            return 'frontend/unverified_jumbo.html'

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        if self.request.user.profile.verified:
            pass
        return context


class PreauthLoginView(RequirePreauth, LoginView):
    template_name = 'preauth/login.html'


class PreauthRegisterView(RequirePreauth, SignupView):
    template_name = 'preauth/register.html'
    form_class = ClassicSignupForm


from django.contrib.auth import logout as auth_logout


def logout(request):
    # We roll our own logout view as the allauth one needs a POST
    auth_logout(request)
    return redirect('/')


def update_request(request):
    if request.POST:
        form = UpdateRequestMake(request.POST)
        form.data = form.data.copy()
        if form.is_valid():
            ur = form.save()
            ur.request_made_by = request.user
            ur.save()
            return HttpResponse(content="ok")
    response = HttpResponse(content="bad")
    response.status_code = 400
    return response


def design(request):
    return render(request, 'design.html')


def inspect_api(request):
    """API for showing version and build times of instance. Protected with basic key."""
    key = request.GET.get('key', None)
    key_hash = hashlib.sha256('{salt}{key}'.format(salt=settings.INSPECT_API_KEY_SALT, key=key)).hexdigest()

    if key and key_hash == settings.INSPECT_API_KEY_HASH:
        return JsonResponse({
            'version_tag': VERSION['tag'],
            'version_released': VERSION['released'],
            'build_time_pre': get_time(PRE_FILE),
            'build_time_post': get_time(POST_FILE),
            'build_time_deploy': get_time(DEPLOY_FILE),
        })
    else:
        return JsonResponse({
            'error': True,
            'message': 'Missing or invalid key',
        })


def handler400(request):
    return render(request, '500.html', status=400)


def handler403(request):
    return render(request, '403.html', status=403)


def handler404(request):
    return render(request, '404.html', status=404)


def handler500(request):
    return render(request, '500.html', status=500)

src/xsd_training/views/base.py
from __future__ import unicode_literals

from django.core.exceptions import PermissionDenied

from xsd_training.forms import *


class TraineeViewMixin(object):
    def get_trainee(self):
        if 't_pk' in self.kwargs:
            return MemberProfile.objects.get(pk=self.kwargs['t_pk'])
        else:
            return self.request.user.profile

    def is_allowed(self, user):
        return self.get_trainee() == user.profile or is_instructor(user)

    def dispatch(self, request, *args, **kwargs):
        if self.is_allowed(request.user):
            return super(TraineeViewMixin, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied


class TraineeFormMixin(TraineeViewMixin, object):
    def get_context_data(self, **kwargs):
        context = super(TraineeFormMixin, self).get_context_data(**kwargs)
        context['trainee'] = self.get_trainee()
        return context

src/xsd_frontend/templates/base/bulk_select_members.html
{% if method == "GET" %}
    <form action="." method="GET">
{% else %}
    <form action="action/add/" method="POST">
    {% csrf_token %}
{% endif %}
    <p>
        <input type="text" id="token-input" name="names"/>
    </p>
    <p>
        <button type="submit" class="btn btn-primary"><i class="fa fa-chevron-right"></i> Select</button>
    </p>

    <script type="text/javascript" src="/members/api/tokeninput-data.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#token-input").tokenInput(data, {
                resultsLimit: 8,
                searchDelay: null,
                animateDropdown: false,
                hintText: 'Type in part of a members name...',
                noResultsText: 'No members by that name'
            });
        });
    </script>
</form>

src/xsd_frontend/templates/base/field.html
{% load widget_tweaks %}
<div class="form-group {% if field.errors %}has-error{% endif %}">

    {% render_field field class+="form-control" %}

    {% for error in field.errors %}
        <div class="form-control-feedback">
            {{ error }}
        </div>
    {% endfor %}

    {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
    {% endif %}
</div>

src/xsd_frontend/templates/base/update_request_list.html
<div class="row">
    <div class="col-md-12">
        <h2>Update Requests</h2>
        <div class="accordion" id="accordion-ur">

            {% for ur in update_requests %}

                <div class="accordion-group">
                    <div class="accordion-heading">
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion-ur"
                           href="#ur{{ ur.pk }}">
                            <div class="alignright">
                                {% if not ur.completed and ur.response_body %}
                                    <span class="label label-warning">Response Sent</span>
                                {% else %}
                                    <span class="label {% if ur.completed %}label-success{% else %}label-important{% endif %}">{{ ur.completed|yesno:"Fixed,Needs Attention"}}</span>{% endif %}
                            </div>
                            From <strong>{{ ur.request_made_by.get_full_name }}</strong> at {{ ur.sent }}</strong>

                        </a>
                    </div>
                    <div id="ur{{ ur.pk }}" class="accordion-body collapse out">
                        <div class="accordion-inner">
                            <form action="{{ form_action }}" method="POST">
                                <input type="hidden" name="pk" value="{{ ur.pk }}"/>
                                {% csrf_token %}
                                {{ ur.request_body|linebreaks }}
                                {% if update_request_custom %}{% include update_request_custom %}{% endif %}
                                <hr/>
                                <h4>Respond to this Request</h4>
                                <div class="row-fluid">
                                    <div class="span8"><textarea cols="40" id="id_response_body" name="response_body"
                                                                 rows="10">{{ ur.response_body }}</textarea></div>
                                    <div class="span4">
                                        <p>Please note that currently members cannot respond to the message that you put
                                            here, if further information is needed you should seek out the member.</p>

                                        <div class="control-group">
                                            <div class="controls">
                                                <label class="checkbox">
                                                    <input id="id_completed" name="completed" type="checkbox"
                                                           {% if ur.completed %}checked=true{% endif %}/>
                                                    Mark this issue as fixed
                                                </label>
                                            </div>
                                        </div>

                                        <input type="submit" class="btn btn-primary" value="Send"/>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

    </div>
</div>

{% block closing_js %}
    <script type="text/javascript">
        $(document).ready(function () {
            location.hash && $(location.hash + '.collapse').collapse('show');
        });
    </script>
{% endblock %}