src/xSACdb/urls.py
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views.defaults import page_not_found

admin.autodiscover()

handler400 = 'xsd_frontend.views.handler400'
handler403 = 'xsd_frontend.views.handler403'
handler404 = 'xsd_frontend.views.handler404'
handler500 = 'xsd_frontend.views.handler500'

urlpatterns = [
    url(r'^', include('xsd_frontend.urls', namespace='xsd_frontend')),

    url(r'^members/', include('xsd_members.urls', namespace='xsd_members')),

    url(r'^training/', include('xsd_training.urls', namespace='xsd_training')),

    url(r'^sites/', include('xsd_sites.urls', namespace='xsd_sites')),

    url(r'^trips/', include('xsd_trips.urls', namespace='xsd_trips')),

    url(r'^kit/', include('xsd_kit.urls', namespace='xsd_kit')),

    url(r'^about/', include('xsd_about.urls', namespace='xsd_about')),

    url(r'^help/', include('xsd_help.urls', namespace='xsd_help')),

    # Bodge here as accounts/ URLS need to be avaliable under the xsd_auth
    # namespace along with no namespace for access via external libs #185
    url(r'^accounts/', include('allauth.urls', namespace='xsd_auth')),
    url(r'^accounts/', include('allauth.urls')),

    url(r'^hijack/', include('hijack.urls')),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/rq/', include('django_rq.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^health/', include('health_check.urls')),

    url(r'^404/$', page_not_found),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        # url('^activity/', include('actstream.urls')),
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

src/xsd_training/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from xsd_frontend.versioning import VersionHistoryView
from xsd_training.views import *

urlpatterns = [
    url(r'^$', trainee.overview, name='training-overview'),
    url(r'^lessons/$', trainee.lessons, name='training-lessons'),
    url(r'^lessons/(?P<pk>\d+)/$', LessonDetail.as_view(), name='MyLessonDetail'),

    url(r'^feedback$', trainee.all_feedback, name='all-feedback'),

    url(r'^session/new/$', SessionCreate.as_view(), name='SessionCreate'),
    url(r'^session/list/$', SessionList.as_view(), name='SessionList'),
    url(r'^session/(?P<pk>\d+)/$', SessionPlanner.as_view(), name='SessionPlanner'),
    url(r'^session/(?P<pk>\d+)/history/$', VersionHistoryView.as_view(), name='SessionHistory',
        kwargs={'model': Session}),
    url(r'^session/(?P<pk>\d+)/action/(?P<action>\w+)/$', SessionAction.as_view(), name='SessionAction'),
    url(r'^session/(?P<pk>\d+)/complete/$', SessionComplete.as_view(), name='SessionComplete'),
    url(r'^session/(?P<pk>\d+)/delete/$', SessionDelete.as_view(), name='SessionDelete'),

    url(r'^pool-sheet/$', pool_sheet, name='PoolSheet'),
    url(r'^pool-sheet/generate$', pool_sheet_generate, name='PoolSheetGenerate'),

    url(r'^retro/lessons/$', RetroAddLessons.as_view(), name='RetroAddLessons'),

    url(r'^teaching/upcoming/$', InstructorUpcoming, name='InstructorUpcoming'),

    url(r'^trainee/search/$', TraineeNotesSearch.as_view(), name='TraineeNotesSearch'),
    url(r'^trainee/(?P<pk>\d+)/$', TraineeNotes.as_view(), name='TraineeNotes'),
    url(r'^trainee/(?P<t_pk>\d+)/lesson/(?P<pk>\d+)/$', LessonDetail.as_view(), name='TraineeLessonDetail'),
    url(r'^trainee/(?P<t_pk>\d+)/lesson/(?P<l_pk>\d+)/new/$', PerformedLessonCreate.as_view(), name='TraineePerformedLessonCreate'),
    url(r'^trainee/(?P<t_pk>\d+)/lesson/(?P<l_pk>\d+)/(?P<pk>\d+)/$', PerformedLessonUpdate.as_view(), name='TraineePerformedLessonUpdate'),
    url(r'^trainee/(?P<t_pk>\d+)/lesson/(?P<l_pk>\d+)/(?P<pk>\d+)/delete/$', PerformedLessonDelete.as_view(), name='TraineePerformedLessonDelete'),
    url(r'^trainee/(?P<pk>\d+)/set/$', trainee_notes_set, name='TraineeNotesSet'),
    url(r'^trainee/(?P<t_pk>\d+)/qualification/new/$', QualificationCreate.as_view(),
        name='TraineeQualificationCreate'),
    url(r'^trainee/(?P<t_pk>\d+)/qualification/(?P<pk>\d+)/$', QualificationUpdate.as_view(),
        name='TraineeQualificationUpdate'),
    url(r'^trainee/(?P<t_pk>\d+)/qualification/(?P<pk>\d+)/delete/$', QualificationDelete.as_view(),
        name='TraineeQualificationDelete'),

    url(r'^sdc/$', SDCList.as_view(), name='SDCList'),
    url(r'^sdc/reg-interest/$', sdc_register_interest, name='sdc_register_interest'),

    url(r'^sdc/plan/$', PerformedSDCCreate.as_view(), name='PerformedSDCCreate'),
    url(r'^sdc/upcoming/$', PerformedSDCList.as_view(), name='PerformedSDCList'),
    url(r'^sdc/(?P<pk>\d+)/$', PerformedSDCDetail.as_view(), name='PerformedSDCDetail'),
    url(r'^sdc/(?P<pk>\d+)/edit/$', PerformedSDCUpdate.as_view(), name='PerformedSDCUpdate'),
    url(r'^sdc/(?P<pk>\d+)/edit/action/(?P<action>\w+)/$', PerformedSDCAction.as_view(), name='PerformedSDCAction'),
    url(r'^sdc/(?P<pk>\d+)/history/$', VersionHistoryView.as_view(), name='PerformedSDCHistory',
        kwargs={'model': PerformedSDC}),
    url(r'^sdc/(?P<pk>\d+)/complete/$', PerformedSDCComplete.as_view(), name='PerformedSDCComplete'),
    url(r'^sdc/(?P<pk>\d+)/delete/$', PerformedSDCDelete.as_view(), name='PerformedSDCDelete'),
    url(r'^sdc/award/$', SDCAward, name='SDCAward'),

    url(r'^groups/$', TraineeGroupList.as_view(), name='TraineeGroupList'),
    url(r'^groups/new/$', TraineeGroupCreate.as_view(), name='TraineeGroupCreate'),
    url(r'^groups/(?P<pk>\d+)/$', TraineeGroupUpdate.as_view(), name='TraineeGroupUpdate'),
    url(r'^groups/(?P<pk>\d+)/history/$', VersionHistoryView.as_view(), name='TraineeGroupHistory',
        kwargs={'model': TraineeGroup}),
    url(r'^groups/(?P<pk>\d+)/action/(?P<action>\w+)/$', TraineeGroupAction.as_view(),
        name='TraineeGroupAction'),
    url(r'^groups/(?P<pk>\d+)/delete/$', TraineeGroupDelete.as_view(), name='TraineeGroupDelete'),

    url(r'^groups/progress/$', TraineeGroupProgress.as_view(), name='TraineeGroupProgress'),

    url(r'^update-requests/$', TrainingUpdateRequestList.as_view(), name='TrainingUpdateRequestList'),
    url(r'^update-requests/save/$', TrainingUpdateRequestRespond.as_view(),
        name='TrainingUpdateRequestRespond'),
]

src/xsd_training/views/base.py
from __future__ import unicode_literals

from django.core.exceptions import PermissionDenied

from xsd_training.forms import *


class TraineeViewMixin(object):
    def get_trainee(self):
        if 't_pk' in self.kwargs:
            return MemberProfile.objects.get(pk=self.kwargs['t_pk'])
        else:
            return self.request.user.profile

    def is_allowed(self, user):
        return self.get_trainee() == user.profile or is_instructor(user)

    def dispatch(self, request, *args, **kwargs):
        if self.is_allowed(request.user):
            return super(TraineeViewMixin, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied


class TraineeFormMixin(TraineeViewMixin, object):
    def get_context_data(self, **kwargs):
        context = super(TraineeFormMixin, self).get_context_data(**kwargs)
        context['trainee'] = self.get_trainee()
        return context

src/xsd_training/views/instructor.py
from __future__ import unicode_literals

from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import DetailView

from xSACdb.roles.decorators import require_instructor, require_training_officer
from xSACdb.roles.mixins import RequireInstructor
from xSACdb.views import OrderedListView
from xsd_training.forms import *


@require_instructor
def InstructorUpcoming(request):
    def get_upcoming_sessions_by_instructor(instructor):
        now = datetime.datetime.now() + datetime.timedelta(days=1)
        sessions_query = Session.objects.filter(when__gt=now).order_by('when')

        sessions = []

        for session in sessions_query:
            pls = PerformedLesson.objects.filter(session=session)
            involved = False
            pls_teaching = []
            for pl in pls:
                if pl.instructor == instructor:
                    involved = True
                    pls_teaching.append(pl)
            if involved:
                sessions.append((session, pls_teaching))
        return sessions

    instructor = request.user.memberprofile
    upcoming_sessions = get_upcoming_sessions_by_instructor(instructor)

    return render(request, 'instructor_upcoming.html', {
        'upcoming_sessions': upcoming_sessions
    })


class TraineeNotesSearch(RequireInstructor, OrderedListView):
    model = MemberProfile
    template_name = 'xsd_training/trainee/search.html'
    context_object_name = 'trainees'
    order_by = 'last_name'

    def get_queryset(self):
        queryset = super(TraineeNotesSearch, self).get_queryset()
        if 'q' in self.request.GET:
            name = self.request.GET['q']
            queryset = queryset.filter(
                Q(last_name__icontains=name) |
                Q(first_name__icontains=name)
            )
        queryset = queryset.prefetch_related(
            'top_qual_cached',
        )
        return queryset

    def get_context_data(self, **kwargs):
        context = super(TraineeNotesSearch, self).get_context_data()
        if 'q' in self.request.GET:
            context['q'] = self.request.GET['q']
        return context


class TraineeNotes(RequireInstructor, DetailView):
    model = MemberProfile
    template_name = 'xsd_training/trainee/detail.html'
    context_object_name = 'trainee'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(TraineeNotes, self).get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['trainee'] = self.get_object().memberprofile
        pls = PerformedLesson.objects.filter(trainee=self.get_object())
        context['pls'] = pls
        context['planned'] = pls.filter(completed=False, partially_completed=False).count()
        context['partially_completed'] = pls.filter(completed=False, partially_completed=True).count()
        context['completed'] = pls.filter(completed=True, partially_completed=False).count()

        # Forms for trainee updation
        context['current_qual_form'] = MiniQualificationSetForm()
        context['training_for_form'] = MiniTrainingForSetForm()
        context['instructor_form'] = MiniInstructorQualificationSetForm()
        context['sdc_form'] = MiniTraineeSDCAddForm()

        # Forms for modals
        return context


@require_training_officer
def trainee_notes_set(request, pk):
    if 'field' in request.GET:
        trainee_profile = get_object_or_404(MemberProfile, pk=pk)
        if request.GET['field'] == 'training_for':
            if request.GET['qualification'] == "":
                # Remove
                trainee_profile.training_for = None
            else:
                q = get_object_or_404(Qualification, pk=request.GET['qualification'])
                trainee_profile.training_for = q
            trainee_profile.save()
        if request.GET['field'] == 'sdc':
            sdc = get_object_or_404(SDC, pk=request.GET['sdc'])
            trainee_profile.add_sdc(sdc)
            trainee_profile.save()
        if request.GET['field'] == 'remove_sdc':
            sdc = get_object_or_404(SDC, pk=request.GET['sdc'])
            trainee_profile.sdcs.remove(sdc)
            trainee_profile.save()

        return redirect(reverse('xsd_training:TraineeNotes', kwargs={'pk': pk}))
    else:
        return HttpResponse('No field specified')

src/xsd_training/views/lessons.py
from __future__ import unicode_literals

from django.contrib import messages
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView

from xSACdb.roles.mixins import RequireInstructor
from xsd_auth.permissions import RequireObjectPermission, RequireAllowed
from xsd_training.forms import *
from xsd_training.views.base import TraineeFormMixin, TraineeViewMixin


class LessonDetail(RequireAllowed, TraineeViewMixin, DetailView):
    model = Lesson
    permission = 'can_view'
    context_object_name = 'lesson'
    template_name = 'xsd_training/trainee/lesson_detail.html'

    def is_allowed(self, user):
        # Trainee may view their lessons
        if self.get_trainee().user == user:
            return True
        # Instructors and training officers may view all
        elif is_instructor(user) or is_training(user):
            return True
        return False

    def get_context_data(self, **kwargs):
        context = super(LessonDetail, self).get_context_data(**kwargs)
        context['trainee'] = self.get_trainee()
        context['pls'] = self.get_object().get_pls(self.get_trainee())
        context['state'] = self.get_object().get_lesson_state(self.get_trainee())
        return context


class PerformedLessonFormMixin(TraineeFormMixin, object):
    def get_lesson(self):
        return Lesson.objects.get(pk=self.kwargs['l_pk'])

    def get_context_data(self, **kwargs):
        context = super(PerformedLessonFormMixin, self).get_context_data(**kwargs)
        context['lesson'] = self.get_lesson()
        return context

    def get_success_url(self):
        return '{}#{}'.format(reverse('xsd_training:TraineeNotes', kwargs={'pk': self.kwargs['t_pk']}),
                              self.kwargs['l_pk'])


class PerformedLessonCreate(RequireInstructor, PerformedLessonFormMixin, CreateView):
    model = PerformedLesson
    template_name = 'xsd_training/trainee/pl_form.html'
    fields = ['date', 'instructor', 'completed', 'partially_completed', 'public_notes',
              'private_notes', ]

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.trainee = self.get_trainee()
        self.object.lesson = self.get_lesson()

        messages.add_message(self.request, messages.SUCCESS,
                             '{} added to {}'.format(self.object.lesson, self.get_trainee().full_name))

        return super(PerformedLessonCreate, self).form_valid(form)


class PerformedLessonUpdate(RequireObjectPermission, PerformedLessonFormMixin, UpdateView):
    model = PerformedLesson
    permission = 'can_edit'
    template_name = 'xsd_training/trainee/pl_form.html'
    fields = ['session', 'date', 'instructor', 'completed', 'partially_completed', 'public_notes',
              'private_notes', ]


class PerformedLessonDelete(RequireObjectPermission, PerformedLessonFormMixin, DeleteView):
    model = PerformedLesson
    permission = 'can_delete'

    def delete(self, request, *args, **kwargs):
        messages.add_message(self.request, messages.ERROR,
                             '{} removed from {}'.format(self.get_lesson(), self.get_trainee().full_name))
        return super(PerformedLessonDelete, self).delete(request, args, kwargs)

src/xsd_training/views/qualifications.py
from __future__ import unicode_literals

from django.contrib import messages
from django.views.generic import CreateView, UpdateView, DeleteView

from xSACdb.roles.mixins import RequireTrainingOfficer
from xsd_training.forms import *
from xsd_training.views.base import TraineeFormMixin


class QualificationFormMixin(TraineeFormMixin, object):
    def get_success_url(self):
        return '{}#qualification-list'.format(
            reverse('xsd_training:TraineeNotes', kwargs={'pk': self.kwargs['t_pk']}))


class QualificationCreate(RequireTrainingOfficer, QualificationFormMixin, CreateView):
    model = PerformedQualification
    form_class = PerformedQualificationForm
    template_name = 'xsd_training/trainee/qualification_form.html'

    def form_valid(self, form):
        """
        If the form is valid, save the associated model.
        """
        self.object = form.save(commit=False)
        self.get_trainee().award_qualification(self.object, actor=self.request.user)

        messages.add_message(self.request, messages.SUCCESS,
                             '{} awarded to {}'.format(self.object.qualification, self.get_trainee().full_name))

        return super(QualificationCreate, self).form_valid(form)


class QualificationUpdate(RequireTrainingOfficer, QualificationFormMixin, UpdateView):
    model = PerformedQualification
    fields = ['mode', 'xo_from', 'signed_off_on', 'signed_off_by', 'notes', ]
    template_name = 'xsd_training/trainee/qualification_form.html'

    def form_valid(self, form):
        messages.add_message(self.request, messages.SUCCESS,
                             '{} updated on {}'.format(self.get_object().qualification, self.get_trainee().full_name))
        return super(QualificationUpdate, self).form_valid(form)


class QualificationDelete(RequireTrainingOfficer, QualificationFormMixin, DeleteView):
    model = PerformedQualification

    def delete(self, request, *args, **kwargs):
        messages.add_message(self.request, messages.ERROR,
                             '{} removed from {}'.format(self.get_object().qualification, self.get_trainee().full_name))
        return super(QualificationDelete, self).delete(request, args, kwargs)

src/xsd_training/templates/xsd_training/modals/lesson_detail.html
<div class="modal fade xsd-lesson-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Lesson</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container-fluid">
                    <div class="row" id="lesson-body">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/xsd_training/templates/xsd_training/modals/qualification_list.html
<div class="modal fade xsd-qualification-modal xsd-qualification-modal--list" tabindex="-1" role="dialog"
     aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Qualifications</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                {% if trainee.qualifications_detail %}
                    <table class="table">
                        <tr>
                            <th>Qualification</th>
                            <th>Mode</th>
                            <th>Dated</th>
                            <th>Signed off by</th>
                            <th>Notes</th>
                        </tr>

                        {% for pq in trainee.qualifications_detail %}
                            <tr>
                                <td>
                                    <i class="fa fa-square xsd-qual-fg--{{ pq.qualification.code }}"
                                       aria-hidden="true"></i>
                                    {{ pq.qualification }}
                                </td>
                                <td>
                                    {{ pq.mode_display }}
                                    {% if pq.mode == 'XO' %}
                                        ({{ pq.xo_from }})
                                    {% endif %}
                                </td>
                                <td>
                                    {% if pq.signed_off_on %}
                                        {{ pq.signed_off_on }}
                                    {% else %}
                                        <em>Unknown</em>
                                    {% endif %}
                                </td>
                                <td>
                                    {% if pq.signed_off_by %}
                                        {{ pq.signed_off_by }}
                                    {% else %}
                                        <em>Unknown</em>
                                    {% endif %}
                                </td>
                                <td>
                                    {{ pq.notes }}
                                </td>
                                {% if is_training %}
                                    <td>
                                        <div class="btn-group">
                                            <a class="btn btn-secondary"
                                               href="{% url 'xsd_training:TraineeQualificationUpdate' trainee.pk pq.pk %}">
                                                <i class="fa fa-pencil"></i>
                                            </a>
                                            <form action="{% url 'xsd_training:TraineeQualificationDelete' trainee.pk pq.pk %}"
                                                  method="POST"
                                                  onsubmit="return confirm('Are you sure you want to delete {{ pq.qualification }} from {{ trainee.full_name }}?');">
                                                {% csrf_token %}
                                                <button class="btn btn-outline-danger" data-qualification-delete
                                                        type="submit">
                                                    <i class="fa fa-times"></i>
                                                </button>
                                            </form>
                                        </div>
                                    </td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    </table>
                {% else %}
                    <div class="alert alert-info">
                        {{ trainee.first_name }} has no qualifications on record.
                    </div>
                {% endif %}
                {% if is_training %}
                    <a class="btn btn-secondary" href="{% url 'xsd_training:TraineeQualificationCreate' trainee.pk %}">
                        <i class="fa fa-plus"></i>
                        Award New
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
</div>