src/xSACdb/urls.py
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views.defaults import page_not_found

admin.autodiscover()

handler400 = 'xsd_frontend.views.handler400'
handler403 = 'xsd_frontend.views.handler403'
handler404 = 'xsd_frontend.views.handler404'
handler500 = 'xsd_frontend.views.handler500'

urlpatterns = [
    url(r'^', include('xsd_frontend.urls', namespace='xsd_frontend')),

    url(r'^members/', include('xsd_members.urls', namespace='xsd_members')),

    url(r'^training/', include('xsd_training.urls', namespace='xsd_training')),

    url(r'^sites/', include('xsd_sites.urls', namespace='xsd_sites')),

    url(r'^trips/', include('xsd_trips.urls', namespace='xsd_trips')),

    url(r'^kit/', include('xsd_kit.urls', namespace='xsd_kit')),

    url(r'^about/', include('xsd_about.urls', namespace='xsd_about')),

    url(r'^help/', include('xsd_help.urls', namespace='xsd_help')),

    # Bodge here as accounts/ URLS need to be avaliable under the xsd_auth
    # namespace along with no namespace for access via external libs #185
    url(r'^accounts/', include('allauth.urls', namespace='xsd_auth')),
    url(r'^accounts/', include('allauth.urls')),

    url(r'^hijack/', include('hijack.urls')),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/rq/', include('django_rq.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^health/', include('health_check.urls')),

    url(r'^404/$', page_not_found),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        # url('^activity/', include('actstream.urls')),
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

src/xsd_trips/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from views import *

urlpatterns = [
    url(r'^$', TripListUpcoming.as_view(), name='TripListUpcoming'),
    url(r'^archive/$', TripListArchive.as_view(), name='TripListArchive'),
    url(r'^my/$', TripListMine.as_view(), name='TripListMine'),
    url(r'^admin/$', TripListAdmin.as_view(), name='TripListAdmin'),

    url(r'^new/$', TripCreate.as_view(), name='TripCreate'),

    url(r'^(?P<pk>\d+)/$', TripDetail.as_view(), name='TripDetail'),
    url(r'^(?P<pk>\d+)/edit/$', TripUpdate.as_view(), name='TripUpdate'),
    url(r'^(?P<pk>\d+)/history/$', TripHistory.as_view(), name='TripHistory'),
    url(r'^(?P<pk>\d+)/action/(?P<action>\w+)/$', TripSet.as_view(), name='TripSet'),
    url(r'^(?P<pk>\d+)/delete/$', TripDelete.as_view(), name='TripDelete'),
    url(r'^(?P<pk>\d+)/roster/$', TripAttendeeRosterDump.as_view(), name='TripAttendeeRosterDump'),
]

src/xsd_trips/models/trip.py
from __future__ import unicode_literals

import datetime

from actstream.actions import follow
from django.core.urlresolvers import reverse
from django.db import models

from xsd_members.models import MemberProfile
from .trip_fake import TripFakeDataMixin
from .trip_manager import TripManager
from .trip_member import TripMember, TripMemberMixin
from .trip_permission import TripPermissionMixin
from .trip_state import *


@reversion.register()
class Trip(TripStateMixin,
           TripPermissionMixin,
           TripMemberMixin,
           TripFakeDataMixin,
           models.Model):
    """Representation of a trip"""

    objects = TripManager()

    owner = models.ForeignKey(MemberProfile, related_name='trip_owner', verbose_name='Organiser')

    name = models.CharField(max_length=64, help_text='Friendly name.')

    date_start = models.DateField(verbose_name='Departs', help_text='dd/mm/yyyy')
    date_end = models.DateField(blank=True, null=True, verbose_name='Returns', help_text='dd/mm/yyyy')

    cost = models.DecimalField(decimal_places=2, max_digits=6, blank=True, null=True,
                               help_text='Advertised cost of trip.')

    spaces = models.PositiveIntegerField(blank=True, null=True, help_text='Number of spaces to advertise.')

    description = models.TextField(blank=True, help_text='Viewable by all members.')

    max_depth = models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum depth',
                                            help_text='Indication of the maximum planned depth of dives.')
    min_qual = models.ForeignKey('xsd_training.Qualification', blank=True, null=True,
                                 verbose_name='Minimum qualification',
                                 help_text='Indication of the minimum qualification needed to participate on this trip\'s diving.')

    # Copy states from states
    STATE_DENIED = STATE_DENIED
    STATE_NEW = STATE_NEW
    STATE_APPROVED = STATE_APPROVED

    STATE_CANCELLED = STATE_CANCELLED
    STATE_OPEN = STATE_OPEN
    STATE_CLOSED = STATE_CLOSED
    STATE_COMPLETED = STATE_COMPLETED

    STATES = (
        (STATE_DENIED, 'Denied'),
        (STATE_NEW, 'New'),
        (STATE_APPROVED, 'Approved'),
        (STATE_CANCELLED, 'Cancelled'),
        (STATE_OPEN, 'Open'),
        (STATE_CLOSED, 'Closed'),
        (STATE_COMPLETED, 'Completed'),
    )

    state = models.IntegerField(choices=STATES, default=STATE_NEW)

    members = models.ManyToManyField('xsd_members.MemberProfile', blank=True, through=TripMember,
                                     related_name='trip_members')

    @property
    def uid(self):
        return "T{:0>4d}".format(self.pk)

    @property
    def date_final(self):
        """As date_end is optional this will match either that or date_start"""
        return self.date_end or self.date_start

    @property
    def in_past(self):
        return self.date_final < datetime.date.today()

    @property
    def duration(self):
        """Return number of days"""
        if self.date_end:
            return (self.date_end - self.date_start).days + 1
        else:
            return None

    def get_absolute_url(self):
        return reverse('xsd_trips:TripDetail', kwargs={'pk': self.pk})

    def save(self, **kwargs):
        if not self.pk:
            # If new ensure the owner follows their trip
            super(Trip, self).save(**kwargs)
            follow(self.owner.user, self, actor_only=False)
        else:
            super(Trip, self).save(**kwargs)

    def __unicode__(self):
        return '{}'.format(self.name)

src/xsd_trips/models/trip_manager.py
from __future__ import unicode_literals

import datetime
from django.db import models

from .trip_state import *


class TripManager(models.Manager):
    def all(self, *args, **kwargs):
        return super(TripManager, self).all(*args, **kwargs).order_by('date_start')

    def upcoming_all(self):
        return self.filter(date_start__gte=datetime.date.today() - datetime.timedelta(days=14)).order_by('date_start')

    def upcoming(self):
        """Approved trips in the future"""
        return self.upcoming_all().filter(state__gte=self.model.STATE_CANCELLED)

    def private(self):
        """Admin view of denied, new and approved trips"""
        return self.filter(state__lte=self.model.STATE_APPROVED).order_by('date_start')

    def past(self):
        """Approved trips in the future"""
        return self.filter(date_end__lte=datetime.date.today()).order_by('-date_start')

src/xsd_trips/forms.py
from __future__ import unicode_literals

from django import forms
from django.core.exceptions import ValidationError

from xsd_trips.models import Trip


class TripForm(forms.ModelForm):
    class Meta:
        model = Trip
        fields = (
            'name',
            'date_start',
            'date_end',
            'cost',
            'spaces',
            'max_depth',
            'min_qual',
            'description',
        )

    def clean_date_end(self):
        cleaned_data = super(TripForm, self).clean()
        start_date = cleaned_data.get('date_start')
        end_date = cleaned_data.get('date_end')
        if start_date and end_date and end_date < start_date:
            raise ValidationError('End date should be greater than start date.')
        return end_date

src/xsd_training/views/base.py
from __future__ import unicode_literals

from django.core.exceptions import PermissionDenied

from xsd_training.forms import *


class TraineeViewMixin(object):
    def get_trainee(self):
        if 't_pk' in self.kwargs:
            return MemberProfile.objects.get(pk=self.kwargs['t_pk'])
        else:
            return self.request.user.profile

    def is_allowed(self, user):
        return self.get_trainee() == user.profile or is_instructor(user)

    def dispatch(self, request, *args, **kwargs):
        if self.is_allowed(request.user):
            return super(TraineeViewMixin, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied


class TraineeFormMixin(TraineeViewMixin, object):
    def get_context_data(self, **kwargs):
        context = super(TraineeFormMixin, self).get_context_data(**kwargs)
        context['trainee'] = self.get_trainee()
        return context

src/xsd_trips/views.py
from __future__ import unicode_literals

import csv
import datetime

import reversion
from django.conf import settings
from django.contrib import messages
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse
from django.template.defaultfilters import slugify
from django.utils.functional import cached_property
from django.views.generic import DetailView
from django.views.generic import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView

from models import Trip
from xSACdb.roles.functions import is_trips
from xSACdb.roles.mixins import RequireVerified, RequirePermission, RequireTripsOfficer
from xSACdb.views import ActionView
from xsd_frontend.activity import DoAction
from xsd_frontend.versioning import VersionHistoryView
from xsd_members.bulk_select import get_bulk_members
from xsd_members.models import MemberProfile
from xsd_trips.forms import TripForm
from xsd_trips.models.trip_member import TripMember


class BaseTripListView(ListView):
    model = Trip
    template_name = 'xsd_trips/list.html'
    context_object_name = 'trips'
    paginate_by = settings.PAGINATE_BY


class TripListUpcoming(RequireVerified, BaseTripListView):
    """Current & future trips"""

    def get_queryset(self):
        if is_trips(self.request.user):
            return Trip.objects.upcoming_all().select_related()
        else:
            return Trip.objects.upcoming().select_related()


class TripListArchive(RequireVerified, BaseTripListView):
    """Past trips"""
    queryset = Trip.objects.past().select_related()


class TripListMine(RequireVerified, BaseTripListView):
    """Admin view of denied, new and approved trips"""

    def get_queryset(self):
        return super(TripListMine, self).get_queryset().filter(owner=self.request.user.get_profile()).order_by(
            '-date_start')


class TripListAdmin(RequireTripsOfficer, BaseTripListView):
    """Admin view of denied, new and approved trips"""
    queryset = Trip.objects.private().select_related()


class TripCreate(RequireVerified, CreateView):
    model = Trip
    form_class = TripForm
    template_name = 'xsd_trips/edit.html'

    def form_valid(self, form):
        with DoAction() as action, reversion.create_revision():
            # Patch in setting the trip owner
            trip = form.save(commit=False)
            # trip.owner = self.request.user.profile
            trip.owner = self.request.user.profile
            trip.save()
            action.set(actor=self.request.user, verb='requested approval for trip', target=trip, style='trip-create')
            return super(TripCreate, self).form_valid(form)


class TripDetail(RequireVerified, RequirePermission, DetailView):
    model = Trip
    permission = 'can_view'
    template_name = 'xsd_trips/detail.html'

    def get_queryset(self):
        return super(TripDetail, self).get_queryset().select_related()

    def get_context_data(self, **kwargs):
        context = super(TripDetail, self).get_context_data(**kwargs)
        context['page_title'] = self.object.name
        # To populate warning dialogue
        context['export_csv_columns'] = TripAttendeeRosterDump.COLUMNS
        return context


class TripHistory(RequirePermission, VersionHistoryView):
    versioned_model = Trip
    permission = 'can_view_history'

    def get_permission_object(self):
        return Trip.objects.get(pk=self.kwargs['pk'])


class TripUpdate(RequireVerified, RequirePermission, UpdateView):
    model = Trip
    form_class = TripForm
    permission = 'can_edit'
    template_name = 'xsd_trips/edit.html'

    def get_queryset(self):
        return super(TripUpdate, self).get_queryset().select_related()

    def get_context_data(self, **kwargs):
        context = super(TripUpdate, self).get_context_data(**kwargs)
        context['page_title'] = 'Edit Trip'
        return context

    def form_valid(self, form):
        with DoAction() as action, reversion.create_revision():
            action.set(actor=self.request.user, verb='updated trip', target=self.get_object(), style='trip-update')
            return super(TripUpdate, self).form_valid(form)


class TripSet(RequireVerified, ActionView):
    model = Trip

    def deny(self, request):
        self.get_object().set_denied(request.user)

    def approve(self, request):
        self.get_object().set_approved(request.user)

    def cancel(self, request):
        self.get_object().set_cancelled(request.user)

    def open(self, request):
        self.get_object().set_open(request.user)

    def close(self, request):
        self.get_object().set_closed(request.user)

    def complete(self, request):
        self.get_object().set_completed(request.user)

    def add(self, request):
        members = get_bulk_members(request)
        new_tripmembers = self.get_object().add_members(members=members, actor=self.request.user)
        if len(new_tripmembers) > 0:
            messages.add_message(self.request, messages.SUCCESS,
                                 'Added {} members to {}'.format(len(new_tripmembers), self.get_object()))
        else:
            messages.add_message(self.request, messages.WARNING, 'No members added')

    def remove(self, request):
        members = [MemberProfile.objects.get(pk=request.POST['pk'])]
        self.get_object().remove_members(members=members, actor=self.request.user)
        messages.add_message(self.request, messages.SUCCESS,
                             'Removed {} member from {}'.format(len(members), self.get_object()))


class TripDelete(RequirePermission, DeleteView):
    model = Trip
    permission = 'can_delete'
    template_name = 'base/delete.html'
    success_url = reverse_lazy('xsd_trips:TripListUpcoming')

    def delete(self, request, *args, **kwargs):
        messages.add_message(self.request, messages.ERROR,
                             settings.CLUB['trip_delete_success'].format(self.get_object().name))
        return super(TripDelete, self).delete(request, *args, **kwargs)


class TripAttendeeRosterDump(View):
    model = TripMember

    COLUMNS = (
        ('name', 'full_name'),
        ('gender', 'gender'),
        ('date_of_birth', 'date_of_birth'),
        ('address', 'address'),
        ('postcode', 'postcode'),
        ('home_phone', 'home_phone'),
        ('mobile_phone', 'mobile_phone'),
        ('email', 'email'),
        ('next_of_kin_name', 'next_of_kin_name'),
        ('next_of_kin_relation', 'next_of_kin_relation'),
        ('next_of_kin_phone', 'next_of_kin_phone'),
    )

    @cached_property
    def trip(self):
        return Trip.objects.get(pk=self.kwargs['pk'])

    def get_queryset(self):
        return self.model.objects.filter(trip=self.trip)

    def get_filename(self):
        now = datetime.datetime.now().strftime("%Y-%m-%dT%H:%M:%S")
        return '{}_{}_roster.csv'.format(now, slugify(self.trip.name))

    # We use post so 99% of users have to use our form with a data protection notice.
    def post(self, request, *args, **kwargs):
        # Security
        if not self.trip.can_view_attendee_details(request.user):
            raise PermissionDenied

        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="{}"'.format(self.get_filename())

        writer = csv.writer(response)

        writer.writerow([header[0] for header in self.COLUMNS])
        for attendee in self.get_queryset():
            writer.writerow([getattr(attendee.member, column[1]) for column in self.COLUMNS])
        return response

src/xsd_trips/templates/xsd_trips/base.html
{% extends 'base_template.html' %}
{% load navigation %}

{% block content %}
<div class="xsd-module-row">

    <div class="xsd-module-nav">
    {% module_nav %}
    </div>

    <div class="xsd-module-content">
    {% block trips_content %}
    No Content
    {% endblock %}
    </div>

</div>

{% endblock %}

src/xsd_trips/templates/xsd_trips/detail.html
{% extends 'xsd_trips/base.html' %}
{% load permissions %}
{% load markdown %}

{% block trips_content %}
    <div class="row">
        <div class="col">
            <h1>
                {{ trip.uid }} |
                {{ trip.name }}
            </h1>
        </div>
        <div class="col-xs-2">
            {% permission request.user can_view_history trip %}
                <a href="{% url 'xsd_trips:TripHistory' trip.pk %}" class="btn btn-secondary"><i
                        class="fa fa-history"></i> History</a>
            {% endpermission %}
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">

            {% if is_trips %}
                <div class="alert alert-info">
                    <i class="fa fa-info-circle"></i> {{ trip.officer_help_text }}
                </div>
            {% elif trip.owner == profile %}
                <div class="alert alert-info">
                    <i class="fa fa-info-circle"></i> {{ trip.owner_help_text }}
                </div>
            {% endif %}

            <div >
                {% permission request.user can_edit trip %}
                    <a href="{% url 'xsd_trips:TripUpdate' trip.pk %}" class="btn btn-outline-primary"><i
                            class="fa fa-pencil"></i> Edit</a>
                {% endpermission %}

                {% permission request.user can_approve trip %}
                    <form method="POST" action="action/approve/">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Approve</button>
                    </form>
                {% endpermission %}

                {% permission request.user can_deny trip %}
                    <form method="POST" action="action/deny/">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger"><i class="fa fa-times"></i> Deny</button>
                    </form>
                {% endpermission %}

                {% permission request.user can_open trip %}
                    <form method="POST" action="action/open/">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-primary"><i class="fa fa-play"></i> Open</button>
                    </form>
                {% endpermission %}

                {% permission request.user can_close trip %}
                    <form method="POST" action="action/close/">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-primary"><i class="fa fa-stop"></i> Close</button>
                    </form>
                {% endpermission %}

                {% permission request.user can_cancel trip %}
                    <form method="POST" action="action/cancel/">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-danger"><i class="fa fa-ban"></i> Cancel</button>
                    </form>
                {% endpermission %}

                {% permission request.user can_delete trip %}
                    {% csrf_token %}
                    <button class="btn btn-outline-danger" data-toggle="modal" data-target="#deleteModal">
                        <i class="fa fa-trash"></i> Delete
                    </button>
                {% endpermission %}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <dl class="card-block">
                    <dt>Organiser</dt>
                    <dd>
                        <a href="{{ trip.owner.get_absolute_url }}" class="no-underline">
                            <img src="{{ trip.owner.avatar_xs }}" class="avatar avatar-xs" alt="Avatar"/>
                            <span class="underline">{{ trip.owner }}</span>
                        </a>
                    </dd>
                    <dt>State</dt>
                    <dd class="{{ trip.state_class }}-detail">
                        <i class="{{ trip.state_class }}-icon"></i>
                        {{ trip.get_state_display }}
                        {% if is_trips or trip.owner == profile %}
                            {% if trip.is_public %}
                                <em>(public)</em>
                            {% else %}
                                <em>(hidden)</em>
                            {% endif %}
                        {% endif %}
                    </dd>
                    <dt>Departs</dt>
                    <dd>{{ trip.date_start }}</dd>
                    <dt>Returns</dt>
                    <dd>
                        {% if trip.date_end %}
                            {{ trip.date_end }}
                            <em>({{ trip.duration }} day{{ trip.duration|pluralize:"s" }})</em>
                        {% else %}
                            <em>Unknown</em>
                        {% endif %}
                    </dd>
                    <dt>Cost</dt>
                    <dd>
                        {% if trip.cost %}£ {{ trip.cost }}{% else %}<em>Unknown</em>{% endif %}
                    </dd>
                    <dt>Spaces</dt>
                    <dd>
                        {% if trip.spaces %}
                            {% if trip.is_public %}
                                {{ trip.spaces_left }} / {{ trip.spaces }}
                                {% if trip.spaces_over > 0 %}
                                    <strong class="red">({{ trip.spaces_over }} over)</strong>
                                {% endif %}
                            {% else %}
                                {{ trip.spaces }}
                            {% endif %}
                        {% else %}
                            <em>Unknown</em>
                        {% endif %}
                    </dd>
                    <dt>Maximum Depth</dt>
                    <dd>{% if trip.max_depth %}{{ trip.max_depth }} metres{% else %}<em>Unknown</em>{% endif %}</dd>
                    <dt>Minimum Qualification</dt>
                    <dd>{{ trip.min_qual }}</dd>
                </dl>
            </div>
        </div>

        <div class="col-md-6">
            {{ trip.description | markdown }}
        </div>
    </div>
    {% if trip.is_public %}
        <div class="row">
            <div class="col-md-6">
                <h4>Attendees
                    {% if trip.spaces_taken %}
                        <small class="text-muted">({{ trip.spaces_taken }})</small>
                    {% endif %}
                </h4>
                {% permission request.user can_view_attendee_details trip %}
                    <div class="btn-group">
                        {% if trip.spaces_taken > 0 %}
                            <button type="button" class="btn btn-secondary" data-toggle="modal"
                                    data-target="#exportCSVModal">
                                <i class="fa fa-download"></i> Export CSV Roster
                            </button>
                        {% endif %}
                    </div>
                {% endpermission %}
            </div>
            <div class="col-md-6">
                {% permission request.user can_add trip %}
                    {% include 'base/bulk_select_members.html' %}
                {% endpermission %}
            </div>
            <div class="col-md-12">

                {% if trip.members.count > 0 %}

                    {% include 'xsd_trips/member_list.html' with attendees=trip.attendees %}

                {% else %}

                    <div class="alert alert-info">
                        <i class="fa fa-info-circle"></i> No members have been added.
                    </div>

                {% endif %}
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block modals %}
    {% include 'modal/delete.html' %}
    {% include 'xsd_trips/modal_export.html' %}
{% endblock %}

src/xsd_trips/templates/xsd_trips/edit.html
{% extends 'xsd_trips/base.html' %}
{% load markdown %}
{% load widget_tweaks %}

{% block trips_content %}
    <form action="." method="POST">
        {% csrf_token %}

        {% with WIDGET_ERROR_CLASS='form-control-danger' WIDGET_REQUIRED_CLASS='my_required' %}

            <div class="row">
                <div class="col-md-12">
                    <h1 class="{% if form.name.errors %}has-error{% endif %} trip-name">
                        {% if trip.pk %}{{ trip.uid }} | {% endif %}
                        {% render_field form.name class+="form-control form-control-lg" placeholder="Trip Name" %}
                    </h1>
                    {% for error in form.name.errors %}
                        <div class="has-error">
                            <div class="form-control-feedback">
                                {{ error }}
                            </div>
                        </div>
                    {% endfor %}

                </div>
            </div>
            {% include 'xsd_trips/edit_buttons.html' %}
            <div class="row">
                <div class="col-md-6">
                    <div class="card">
                        <dl class="card-block">
                            {% if trip.pk %}
                                <dt>Organiser</dt>
                                <dd>
                                    <a href="{{ trip.owner.get_absolute_url }}" class="no-underline">
                                        <img src="{{ trip.owner.avatar_xs }}" class="avatar avatar-xs"
                                             alt="Avatar"/>
                                        <span class="underline">{{ trip.owner }}</span>
                                    </a>
                                </dd>
                                <dt>State</dt>
                                <dd>
                                    {{ trip.get_state_display }}
                                </dd>
                            {% endif %}

                            {% include 'xsd_trips/edit_field.html' with field=form.date_start %}
                            {% include 'xsd_trips/edit_field.html' with field=form.date_end %}
                            {% include 'xsd_trips/edit_field.html' with field=form.cost %}
                            {% include 'xsd_trips/edit_field.html' with field=form.spaces %}
                            {% include 'xsd_trips/edit_field.html' with field=form.max_depth %}
                            {% include 'xsd_trips/edit_field.html' with field=form.min_qual %}

                        </dl>
                    </div>
                </div>

                <div class="col-md-6">
                    {% render_field form.description class+="form-control" placeholder="Description" %}
                    <p class="form-text text-muted">
                        Styling with <a href="{{ l10n_club.markdown_help }}" target="_blank">Markdown</a> is supported.
                    </p>
                </div>
            </div>

        {% endwith %}

        {% include 'xsd_trips/edit_buttons.html' %}

    </form>
{% endblock %}

src/xsd_trips/templates/xsd_trips/edit_buttons.html
<div class="row">
    <div class="col-md-12">
        <div class="btn-group" role="group">
            {% if trip.pk %}
                <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save</button>
                <a href="{{ trip.get_absolute_url }}" class="btn btn-secondary">Discard Changes</a>
            {% else %}
                <button type="submit" class="btn btn-success"><i class="fa fa-asterisk"></i> Create</button>
            {% endif %}
        </div>
    </div>
</div>

src/xsd_trips/templates/xsd_trips/edit_field.html
{% load widget_tweaks %}
{% load forms %}
<dt>
    <label for="{{ field.id_for_label }}">
        {{ field.label }}
    </label>
</dt>
<dd class="{% if field.errors %}has-error{% endif %}">
    {% include 'forms/field_input-group.html' with field=field %}

    {% for error in field.errors %}
        <div class="form-control-feedback">
            {{ error }}
        </div>
    {% endfor %}

    {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
    {% endif %}

</dd>

src/xsd_trips/templates/xsd_trips/modal_export.html
<div class="modal fade" id="exportCSVModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Download Attendee Roster</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Using this tool you can download a CSV, loadable into Microsoft Excel or similar, of trip attendees
                    and their personal details. Suitable for sending to Students' Unions and other groups.</p>
                <p>The following is included:</p>
                <ul>
                    {% for column in export_csv_columns %}
                        <li>{{ column.0 }}</li>
                    {% endfor %}
                </ul>
                <p>This download contains <strong>sensitive data</strong>. As such you must take responsibility for its
                    storage and distribution. You may not keep this data for longer than you require it &mdash; in this
                    case that will be after your trip is over on {{ trip.date_final }}.</p>
            </div>
            <div class="modal-footer">
                I accept please
                <form action="{% url 'xsd_trips:TripAttendeeRosterDump' trip.pk %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-warning">
                        <i class="fa fa-download"></i>
                        Download CSV
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>